---
# namespace
apiVersion: v1
kind: Namespace
metadata:
 name: whoami
---
# service
apiVersion: v1
kind: Service
metadata:
 name: whoami
 namespace: whoami
spec:
 ports:
   - name: web
     port: 80
     targetPort: web
 selector:
   app: whoami
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: whoami
 namespace: whoami
spec:
 selector:
   matchLabels:
     app: whoami
 template:
   metadata:
     labels:
       app: whoami
   spec:
     containers:
       - name: whoami
         image: traefik/whoami
         ports:
           - name: web
             containerPort: 80
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: whoami
 namespace: whoami
 annotations:
   cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
 tls:
   - hosts:
       - whoami.eks.enriquemanuel.me
     secretName: wildcard-enriquemanuel-me-tls
 rules:
   - host: whoami.eks.enriquemanuel.me
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: whoami
               port:
                 name: web
