apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-enriquemanuel-me-tls
  namespace: traefik
spec:
  secretName: wildcard-enriquemanuel-me-tls
  dnsNames:
    - "eks.enriquemanuel.me"
    - "*.eks.enriquemanuel.me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
